"""Shop oracle cross-validation: Python populate_shop vs pre-generated fixture.

The fixture ``tests/fixtures/shop_oracle_TESTSEED.json`` was generated by
``scripts/run_shop_oracle.py``, which calls ``populate_shop`` with the same
initial conditions as the Balatro game and records the exact shop contents.

The Python RNG is bit-exact with LuaJIT 2.1 — validated in
``tests/engine/test_rng_sequence.py`` which has hardcoded LuaJIT ground truth
for the shop streams ``cdt``, ``rarity``, and ``Joker1sho``.

Test dimensions
---------------
* Fixture mode (always runs): loads the fixture and asserts Python matches.
* Hardcoded LuaJIT ground truth: selected slots whose values come from
  ``tests/engine/test_rng_sequence.py`` (independently validated).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from jackdaw.engine.rng import PseudoRandom
from jackdaw.engine.shop import populate_shop
from jackdaw.engine.vouchers import get_next_voucher_key

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PATH = PROJECT_ROOT / "tests" / "fixtures" / "shop_oracle_TESTSEED.json"


# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def load_fixture() -> dict:
    with open(FIXTURE_PATH, encoding="utf-8") as f:
        return json.load(f)


def _build_game_state(
    first_shop: bool,
    voucher_key: str | None,
) -> dict[str, Any]:
    """Build the default fresh-run game state matching the oracle generator."""
    return {
        "joker_rate": 20.0,
        "tarot_rate": 4.0,
        "planet_rate": 4.0,
        "spectral_rate": 0.0,
        "playing_card_rate": 0.0,
        "edition_rate": 1.0,
        "enable_eternals_in_shop": True,
        "enable_perishables_in_shop": True,
        "enable_rentals_in_shop": True,
        "banned_keys": set(),
        "used_jokers": {},
        "used_vouchers": {},
        "pool_flags": {},
        "has_showman": False,
        "deck_enhancements": set(),
        "playing_card_count": 52,
        "played_hand_types": set(),
        "shop_vouchers": set(),
        "inflation": 0,
        "discount_percent": 0,
        "booster_ante_scaling": False,
        "has_astronomer": False,
        "shop": {"joker_max": 2},
        "current_round": {"voucher": voucher_key},
        "first_shop_buffoon": not first_shop,
    }


def run_shop(seed: str, ante: int, *, first_shop: bool) -> dict:
    """Run the same pipeline as the oracle generator."""
    rng = PseudoRandom(seed)
    voucher_key = get_next_voucher_key(rng, used_vouchers={}, in_shop=[])
    gs = _build_game_state(first_shop=first_shop, voucher_key=voucher_key)
    result = populate_shop(rng, ante, gs)
    return {
        "voucher_key": voucher_key,
        "joker_keys": [c.center_key for c in result["jokers"]],
        "joker_editions": [c.edition or {} for c in result["jokers"]],
        "joker_eternal": [c.eternal for c in result["jokers"]],
        "joker_perishable": [c.perishable for c in result["jokers"]],
        "joker_rental": [c.rental for c in result["jokers"]],
        "booster_keys": [c.center_key for c in result["boosters"]],
    }


# ---------------------------------------------------------------------------
# Fixture loading (class-scoped to load once per class)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def fixture() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(f"Shop oracle fixture not found: {FIXTURE_PATH}")
    return load_fixture()


# ---------------------------------------------------------------------------
# Mode 1: Fixture-based regression tests
# ---------------------------------------------------------------------------


class TestShopOracleFixture:
    """Validate populate_shop against pre-generated fixture for all test seeds."""

    @pytest.mark.parametrize(
        "case_idx,label",
        [
            (0, "TESTSEED/ante1"),
            (1, "TESTSEED/ante3"),
            (2, "TUTORIAL/ante1"),
        ],
    )
    def test_voucher_matches_fixture(self, fixture, case_idx, label):
        case = fixture["cases"][case_idx]
        actual = run_shop(case["seed"], case["ante"], first_shop=case["first_shop"])
        assert actual["voucher_key"] == case["voucher"], (
            f"{label}: voucher {actual['voucher_key']!r} != {case['voucher']!r}"
        )

    @pytest.mark.parametrize(
        "case_idx,label",
        [
            (0, "TESTSEED/ante1"),
            (1, "TESTSEED/ante3"),
            (2, "TUTORIAL/ante1"),
        ],
    )
    def test_joker_keys_match_fixture(self, fixture, case_idx, label):
        case = fixture["cases"][case_idx]
        actual = run_shop(case["seed"], case["ante"], first_shop=case["first_shop"])
        expected_keys = [j["center_key"] for j in case["jokers"]]
        assert actual["joker_keys"] == expected_keys, (
            f"{label}: joker keys {actual['joker_keys']} != {expected_keys}"
        )

    @pytest.mark.parametrize(
        "case_idx,label",
        [
            (0, "TESTSEED/ante1"),
            (1, "TESTSEED/ante3"),
            (2, "TUTORIAL/ante1"),
        ],
    )
    def test_joker_stickers_match_fixture(self, fixture, case_idx, label):
        case = fixture["cases"][case_idx]
        actual = run_shop(case["seed"], case["ante"], first_shop=case["first_shop"])
        for i, expected_j in enumerate(case["jokers"]):
            assert actual["joker_eternal"][i] == expected_j.get("eternal", False), (
                f"{label} joker[{i}]: eternal mismatch"
            )
            assert actual["joker_perishable"][i] == expected_j.get("perishable", False), (
                f"{label} joker[{i}]: perishable mismatch"
            )
            assert actual["joker_rental"][i] == expected_j.get("rental", False), (
                f"{label} joker[{i}]: rental mismatch"
            )

    @pytest.mark.parametrize(
        "case_idx,label",
        [
            (0, "TESTSEED/ante1"),
            (1, "TESTSEED/ante3"),
            (2, "TUTORIAL/ante1"),
        ],
    )
    def test_booster_keys_match_fixture(self, fixture, case_idx, label):
        case = fixture["cases"][case_idx]
        actual = run_shop(case["seed"], case["ante"], first_shop=case["first_shop"])
        expected_keys = [b["center_key"] for b in case["boosters"]]
        assert actual["booster_keys"] == expected_keys, (
            f"{label}: booster keys {actual['booster_keys']} != {expected_keys}"
        )

    def test_first_booster_buffoon_on_first_shop(self, fixture):
        """First shop always starts with a Buffoon pack in slot 0."""
        from jackdaw.engine.data.prototypes import BOOSTERS

        for case in fixture["cases"]:
            if not case["first_shop"]:
                continue
            boosters = case["boosters"]
            first_key = boosters[0]["center_key"]
            assert BOOSTERS[first_key].kind == "Buffoon", (
                f"seed={case['seed']!r} ante={case['ante']}: "
                f"expected Buffoon pack, got {BOOSTERS[first_key].kind!r}"
            )

    def test_fixture_has_three_cases(self, fixture):
        assert len(fixture["cases"]) == 3


# ---------------------------------------------------------------------------
# Mode 2: Hardcoded LuaJIT ground truth
# ---------------------------------------------------------------------------
# Stream values from tests/engine/test_rng_sequence.py:
#   TESTSEED shop slot 0: cdt=0.3236…, rarity=0.1273… → rarity-1 Joker
#   TESTSEED shop slot 1: cdt=0.5376…, rarity=0.7773… → rarity-2 Joker
#
# These streams are driven by get_next_voucher_key first (advances 'Voucher'
# stream), so the exact keys depend on both the voucher and the joker draws.


class TestShopOracleLuaJITGroundTruth:
    """Assertions based on LuaJIT-validated RNG values from test_rng_sequence.

    The rng_sequence test confirms:
    - TESTSEED cdt1 call-1 → 0.323… → Joker type (< 20/28 threshold)
    - TESTSEED cdt1 call-2 → 0.537… → Joker type
    - TESTSEED rarity1sho call-1 → 0.127… → rarity 1
    - TESTSEED rarity1sho call-2 → 0.777… → rarity 2
    - TESTSEED Joker1sho1 call-1 → j_joker  (from 10-joker pool subset)
    - TESTSEED Joker1sho1 call-2 → j_mad
    """

    def test_testseed_ante1_joker_slots_are_jokers(self):
        """Both TESTSEED ante1 shop slots are Joker-type cards (cdt < 20/28)."""
        from jackdaw.engine.data.prototypes import JOKERS

        result = run_shop("TESTSEED", 1, first_shop=True)
        for i, key in enumerate(result["joker_keys"]):
            if key in JOKERS:
                assert JOKERS[key].rarity in (1, 2, 3, 4), (
                    f"slot {i}: {key!r} has unexpected rarity"
                )

    def test_testseed_ante1_first_joker_is_rarity1(self):
        """TESTSEED ante1 slot-0 rarity roll 0.127… < 0.7 → rarity 1."""
        from jackdaw.engine.data.prototypes import JOKERS

        result = run_shop("TESTSEED", 1, first_shop=True)
        key = result["joker_keys"][0]
        if key in JOKERS:
            assert JOKERS[key].rarity == 1, (
                f"Expected rarity-1 joker in slot 0, got {key!r} (rarity {JOKERS[key].rarity})"
            )

    def test_testseed_ante1_second_joker_is_rarity2(self):
        """TESTSEED ante1 slot-1 rarity roll 0.777… > 0.7 → rarity 2."""
        from jackdaw.engine.data.prototypes import JOKERS

        result = run_shop("TESTSEED", 1, first_shop=True)
        key = result["joker_keys"][1]
        if key in JOKERS:
            assert JOKERS[key].rarity == 2, (
                f"Expected rarity-2 joker in slot 1, got {key!r} (rarity {JOKERS[key].rarity})"
            )

    def test_testseed_ante1_first_booster_is_buffoon(self):
        """TESTSEED ante1 first booster: first-shop Buffoon guarantee."""
        from jackdaw.engine.data.prototypes import BOOSTERS

        result = run_shop("TESTSEED", 1, first_shop=True)
        pack_key = result["booster_keys"][0]
        assert BOOSTERS[pack_key].kind == "Buffoon"

    def test_determinism_same_seed_same_shop(self):
        """Two runs with the same seed produce identical shop contents."""
        r1 = run_shop("TESTSEED", 1, first_shop=True)
        r2 = run_shop("TESTSEED", 1, first_shop=True)
        assert r1["joker_keys"] == r2["joker_keys"]
        assert r1["booster_keys"] == r2["booster_keys"]
        assert r1["voucher_key"] == r2["voucher_key"]

    def test_different_seeds_differ(self):
        """TESTSEED and TUTORIAL produce different shop contents."""
        r1 = run_shop("TESTSEED", 1, first_shop=True)
        r2 = run_shop("TUTORIAL", 1, first_shop=True)
        assert r1["joker_keys"] != r2["joker_keys"] or r1["voucher_key"] != r2["voucher_key"], (
            "Two different seeds should not produce identical shops"
        )

    def test_different_antes_differ(self):
        """TESTSEED ante1 and ante3 produce different shop contents."""
        r1 = run_shop("TESTSEED", 1, first_shop=True)
        r3 = run_shop("TESTSEED", 3, first_shop=False)
        assert r1["joker_keys"] != r3["joker_keys"] or r1["booster_keys"] != r3["booster_keys"]
