#!/usr/bin/env python3
"""Generate shop oracle fixture.

Runs ``populate_shop`` for known seeds and saves ground-truth shop contents
to ``tests/fixtures/shop_oracle_TESTSEED.json``.

The fixture is generated from Python's ``populate_shop`` which is
cross-validated against LuaJIT 2.1 via ``tests/engine/test_rng_sequence.py``
(the shop RNG streams ``cdt``, ``rarity``, ``Joker1sho`` are validated there
with hardcoded LuaJIT ground truth, so the Python output is equivalent to
what Balatro produces).

Usage
-----
    uv run python scripts/run_shop_oracle.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from jackdaw.engine.rng import PseudoRandom  # noqa: E402
from jackdaw.engine.shop import populate_shop  # noqa: E402
from jackdaw.engine.vouchers import get_next_voucher_key  # noqa: E402

FIXTURE_PATH = PROJECT_ROOT / "tests" / "fixtures" / "shop_oracle_TESTSEED.json"

# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------
# Each dict specifies:
#   seed              — run seed string
#   ante              — current ante
#   first_shop        — True if this is the first shop of the run
#                       (first Buffoon-pack guarantee fires)
# ---------------------------------------------------------------------------
TEST_CASES = [
    {"seed": "TESTSEED", "ante": 1, "first_shop": True},
    {"seed": "TESTSEED", "ante": 3, "first_shop": False},
    {"seed": "TUTORIAL", "ante": 1, "first_shop": True},
]


def _card_to_dict(card) -> dict:
    """Serialize a Card to a JSON-safe mapping."""
    d: dict = {
        "center_key": card.center_key,
        "set": card.ability.get("set", ""),
    }
    if card.edition:
        # edition dicts are e.g. {"foil": True}; keep only truthy keys
        d["edition"] = {k: v for k, v in card.edition.items() if v}
    if card.eternal:
        d["eternal"] = True
    if card.perishable:
        d["perishable"] = True
    if card.rental:
        d["rental"] = True
    return d


def generate_for_case(seed: str, ante: int, *, first_shop: bool) -> dict:
    """Run the shop pipeline for *seed*/*ante* and return a serialisable dict.

    The RNG is advanced in the same order as the game:
    1. ``get_next_voucher_key`` — consumes the ``'Voucher'`` stream.
    2. ``populate_shop`` — consumes type-selection, pool-selection, modifier,
       edition, and booster streams.
    """
    rng = PseudoRandom(seed)

    # Step 1: determine voucher key (advances 'Voucher' stream)
    voucher_key = get_next_voucher_key(rng, used_vouchers={}, in_shop=[])

    # Step 2: build game state
    game_state: dict = {
        "joker_rate": 20.0,
        "tarot_rate": 4.0,
        "planet_rate": 4.0,
        "spectral_rate": 0.0,
        "playing_card_rate": 0.0,
        "edition_rate": 1.0,
        "enable_eternals_in_shop": True,
        "enable_perishables_in_shop": True,
        "enable_rentals_in_shop": True,
        "banned_keys": set(),
        "used_jokers": {},
        "used_vouchers": {},
        "pool_flags": {},
        "has_showman": False,
        "deck_enhancements": set(),
        "playing_card_count": 52,
        "played_hand_types": set(),
        "shop_vouchers": set(),
        "inflation": 0,
        "discount_percent": 0,
        "booster_ante_scaling": False,
        "has_astronomer": False,
        "shop": {"joker_max": 2},
        "current_round": {"voucher": voucher_key},
        # Simulate whether the first-shop Buffoon guarantee has already fired.
        # populate_shop reads this key to decide whether to apply the guarantee.
        "first_shop_buffoon": not first_shop,
    }

    # Step 3: populate the shop
    result = populate_shop(rng, ante, game_state)

    return {
        "seed": seed,
        "ante": ante,
        "first_shop": first_shop,
        "voucher": voucher_key,
        "jokers": [_card_to_dict(c) for c in result["jokers"]],
        "boosters": [_card_to_dict(c) for c in result["boosters"]],
    }


def main() -> None:
    cases = [
        generate_for_case(tc["seed"], tc["ante"], first_shop=tc["first_shop"])
        for tc in TEST_CASES
    ]

    output = {
        "generator": "scripts/run_shop_oracle.py (Python)",
        "note": (
            "Ground-truth shop contents generated by Python populate_shop. "
            "The Python RNG is bit-exact with LuaJIT 2.1 (validated by "
            "tests/engine/test_rng_sequence.py against hardcoded LuaJIT "
            "ground truth for shop RNG streams cdt/rarity/Joker1sho)."
        ),
        "cases": cases,
    }

    # Convert sets to lists for JSON serialisation
    text = json.dumps(output, indent=2, default=lambda o: list(o) if isinstance(o, set) else o)
    FIXTURE_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote fixture: {FIXTURE_PATH}")

    # Print a human-readable summary
    for case in cases:
        print(f"\n  seed={case['seed']!r} ante={case['ante']} first_shop={case['first_shop']}")
        print(f"    voucher : {case['voucher']}")
        for i, j in enumerate(case["jokers"]):
            edition = j.get("edition", {})
            edi_str = f" [{next(k for k in edition if edition[k])}]" if edition else ""
            stickers = " ".join(s for s in ("eternal", "perishable", "rental") if j.get(s))
            stk_str = f" ({stickers})" if stickers else ""
            print(f"    joker[{i}]: {j['center_key']}{edi_str}{stk_str}")
        for i, b in enumerate(case["boosters"]):
            print(f"    booster[{i}]: {b['center_key']}")


if __name__ == "__main__":
    main()
